name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Run tests (if you have tests defined)
    - name: Run tests
      run: npm test

   # Run the bot script
    - name: Start the bot
      run: |
        export HELIUS_HTTP_URL=https://api.helius.xyz
        export HELIUS_WS_URL=wss://ws.helius.xyz
        export HELIUS_ECLIPSE_URL=https://eclipse.helius.xyz
        
        export JITO_BLOCK_ENGINE_URL=https://blockengine.jito.xyz
        export JITO_RELAYER_URL=https://relayer.jito.xyz
        export JITO_NTP_URL=https://ntp.jito.xyz

        export WALLET_ADDRESS=FNr2c5oTt1k77BrnbHNFmKzGLjcM3eiyUoVxERkuqh9a
        export WALLET_PRIVATE_KEY=S76RkCW4ADHKVE5AtwmM9gRtk6ToJdYm453dueswwRaKZ8QXadzrCyCH3h4UYsKmQjrnKuopjqha1mx4U51596x

        export TARGET_WALLET=DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj

        export MAX_EXPOSURE_PER_TRADE=1.0
        export STOP_LOSS_PERCENTAGE=20
        export MAX_DAILY_LOSS=1.0
        export MIN_LIQUIDITY=50
        export MAX_SLIPPAGE=1.5
        export GAS_MULTIPLIER=1.2
        export FRONTRUN_DELAY=50
        export COPY_SIZE_PERCENTAGE=90
        export MAX_RETRIES=3
        export REQUEST_TIMEOUT=5000

        export DISCORD_WEBHOOK=your_discord_webhook_url_here
        export TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
        export TELEGRAM_CHANNEL_ID=@alphabeforealpha

        export FAILED_TRADES_THRESHOLD=3
        export MAX_EXECUTION_TIME=1000
        export MIN_PROFIT_THRESHOLD=-0.1

        export DO_IP=161.35.203.118
        export SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCub5cT0ykVReeICrW8gtapBH3NMHQjiY2Fx7vSG6FJiAk4zsC1k25ddrUiiW86NJaMvO34GXFtPa1sTr1wHu+rPQCOjoJao1FFCoI+NPJnyb+kZjUmXFKWqzEZHFRJWUy9I[...]

        node bot.js
