name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      deploy_to_vps:
        description: "Deploy the bot to VPS"
        required: true
        default: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no mahad@161.35.203.118 << 'EOF'
            cd /home/mahad/high-speed-meme-bot  # Path to your bot directory on VPS
            git pull origin main  # Pull latest changes from the main branch
            npm install --production  # Install only production dependencies (optional)
            npm start  # Start the bot using the start script in package.json
          EOF
